/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package socios.presntation;

import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultListModel;
import socios.business.Quota;
import socios.business.QuotaExisteException;
import socios.business.SGQ;
import socios.business.Socio;
import socios.business.SocioExisteException;

/**
 *
 * @author ricardopetronilho
 */
public class JSGQ extends javax.swing.JFrame implements Observer {
    
    /** SGQ (Modelo) é o singleton */
    private SGQ sgq;

    /**
     * Creates new form JSGQ
     */
    public JSGQ() {
        initComponents();
        this.setResizable(false);
        
        this.sgq = new SGQ();
        /** Este JFrame regista-se como Observador do SGQ para poder actualizar o ecran */
        this.sgq.addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        RegistarSocioMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestão de Quotas");

        jList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Sem Sócios registados" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jList);

        jMenu1.setText("File");

        RegistarSocioMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        RegistarSocioMenuItem.setText("Registar Sócio");
        RegistarSocioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistarSocioMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(RegistarSocioMenuItem);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistarSocioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistarSocioMenuItemActionPerformed
        new JRegistarSocio(this).setVisible(true);
    }//GEN-LAST:event_RegistarSocioMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListMouseClicked
        
        int index = -1;
        
        /* mouse double-click */
        if (evt.getClickCount() == 2) {   
            if ( (index = this.jList.locationToIndex(evt.getPoint())) >= 0 ) {
                
                //TODO obter código do Sócio
                new JVisualizarQuotas(this, "1").setVisible(true);
            }
        }
    }//GEN-LAST:event_jListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JSGQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JSGQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JSGQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JSGQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JSGQ().setVisible(true);
            }
        });
    }
    
    /**
     * Atualiza a informação de todos os Sócios.
     * @param o Objeto que está a ser observado.
     * @param arg obejto transmitido pelo objeto observado.
     */
    @Override
    public void update(Observable o, Object arg) {
        DefaultListModel model = new DefaultListModel();
        for(Socio s: this.sgq.getSocios().values())
            model.addElement(s.toString());
        this.jList.setModel(model);
    }
    
    /**
     * Adiciona um sócio ao SGQ.
     * @param socio
     * @throws SocioExisteException 
     */
    /** Necessária no JRegistarSócio */
    public void addSocio(Socio socio) throws SocioExisteException {
        this.sgq.addSocio(socio);
    }
    
    /**
     * Adiciona um Observer a um Sócio.
     * @param cod código de identificação do código.
     * @param o Observer.
     */
    /** Necessária no JVisualizarQuota para que a JFrame (JVisualizarQuota)
      * consiga observar as Quotas do Sócio selecionado.
      */
    public void addObserverToSocio(String cod, Observer o) {
        this.sgq.addObserverToSocio(cod, o);
    }
    
    /**
     * Devolve a informação de um Sócio.
     * @param cod código de identificação do código.
     * @return retorna a informação de um Sócio.
     */
    public Socio getSocio(String cod) {
        return this.sgq.getSocios().get(cod);
    }
    
    /**
     * Adiciona uma Quota ao Sócio.
     * @param cod código de identificação do código.
     * @param q Quota a ser adicionada.
     * @throws QuotaExisteException 
     */
    /** Necessária no JRegistarQuota */
    public void addQuota(String cod, Quota q) throws QuotaExisteException {
        this.sgq.addQuota(cod, q);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem RegistarSocioMenuItem;
    private javax.swing.JList<String> jList;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
