/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package socios.presntation;

import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import socios.business.Quota;
import socios.business.Socio;

/**
 *
 * @author ricardopetronilho
 */
public class JVisualizarQuotas extends JFrame implements Observer {
    
    /* Parent window -> para conseguir tranferir a informação do Sócio (criado) para a window principal */
    private JSGQ parent; 
    private String cod;
    
    /**
     * Creates new form JVisualizarQuotas
     */
    public JVisualizarQuotas(JSGQ parent, String cod) {
        initComponents();
        this.setResizable(false);
     
        this.parent = parent;
        
        this.cod = cod;
        /** Sócio está a ser observado por esta window */
        this.parent.addObserverToSocio(cod, this);
        
        this.initJList();
    }
    
    private void initJList() {
        DefaultListModel model = new DefaultListModel();
        for (Quota q: this.parent.getSocio(this.cod).getQuotas().values())
            model.addElement(q.toString());
        this.jList1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setTitle("Visualizar Quotas");

        jButton1.setText("Registar Quota");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Sem Quotas registadas" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new JRegistarQuota(this.parent, this.cod).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Atualiza a lista de Quotas do Sócio observado.
     * @param o Sócio observado
     * @param arg Quotas alteradas
     */
    @Override
    public void update(Observable o, Object arg) {
        DefaultListModel model = new DefaultListModel();
        for ( Quota q: this.parent.getSocio(this.cod).getQuotas().values() )
            model.addElement(q.toString());
        this.jList1.setModel(model);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
